services:
  hardhat:
    build:
      context: ./hardhat-app
    container_name: hardhat-node
    ports:
      - 8545:8545
    command: tail -f /dev/null
    networks:
      - wave-network
  webapp:
    build:
      context: ./web-app
    container_name: "webapp"
    ports:
      - 8080:8080
    volumes:
      - ../src/web-app/src:/usr/src/app/src
    networks:
      - wave-network

networks:
  wave-network: {}