services:
  hardhat:
    build:
      context: ./hardhat-app
    container_name: hardhat-node
    ports:
      - 8545:8545
    command: tail -f /dev/null
    networks:
      - wave-network
  react:
    image: node:18-alpine3.16
    container_name: "react"
    working_dir: /app
    volumes:
      - ../web-app:/app
    command: tail -f /dev/null


networks:
  wave-network: {}