services:
  hardhat:
    build:
      context: ./hardhat-app
    container_name: hardhat-node
    ports:
      - 8545:8545
    command: tail -f /dev/null
    networks:
      - wave-network
  node:
    build:
      context: ./web-app
    container_name: "node"
    ports:
      - 8080:8080
    volumes:
      - ../web-app:/app

networks:
  wave-network: {}