services:
  node:
    build:
      context: ./hardhat-app
    container_name: hardhat-node
    ports:
      - 8545:8545
    command: tail -f /dev/null
    networks:
      - wave-network

networks:
  wave-network: {}