services:
  hardhat:
    build:
      context: ./hardhat-app
    container_name: hardhat-node
    ports:
      - 8545:8545
    command: tail -f /dev/null
    networks:
      - wave-network
  node:
    tty: true
    stdin_open: true
    build:
      context: ./web-app
    container_name: "node"
    ports:
      - 8080:8080
    volumes:
      - ../src/web-app:/usr/src/app
    command: yarn start
    networks:
      - wave-network

networks:
  wave-network: {}